#!/bin/sh

# This script configures the VM for the image-allow-list feature.

# shellcheck shell=ash

set -o errexit -o nounset

# Create nobody user and group for nginx.
addgroup -S -g 65534 nobody 2>/dev/null || true
adduser -S -D -H -h /dev/null -s /sbin/nologin -u 65534 -G nobody -g nobody nobody 2>/dev/null || true

# Install mkcert and create default certs for localhost.
export CAROOT=/run/mkcert
mkdir -p $CAROOT
cd $CAROOT
mkcert -install
mkcert localhost
chown -R nobody:nobody $CAROOT

# configure proxy only when image-allow-list exists
ial=/usr/local/openresty/nginx/conf/image-allow-list.conf
setproxy="[ -f $ial ] && supervise_daemon_args=\"-e HTTPS_PROXY=http://127.0.0.1:3128 \$supervise_daemon_args\""
sed -i "\#-f $ial#d" /etc/init.d/containerd
sed -i "/^supervise_daemon_args/a $setproxy" /etc/init.d/containerd

# openresty is backgrounding itself (and writes its own pid file)
sed -i 's/^command_background/#command_background/' /etc/init.d/openresty

# Make sure openresty log directory exists
install -d -m755 /var/log/openresty
