version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directories:
  - "/"
  - "/.github/actions/*/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 12
  labels: ["component/dependencies"]

# Maintain dependencies for npm
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 12
  labels: ["component/dependencies"]
  ignore:
  - # Needs to be updated along with NodeJS version.
    dependency-name: "@types/node"
    update-types: [version-update:semver-major]
  - # We don't utilize @rancher/shell in a meaningful way. It is safe to
    # ignore until we arrive a solution that uses it.
    dependency-name: "@rancher/shell"
    versions: [">0.1"]
  - # We are currently using @vue/cli-service which depends on an older version
    # of webpack.  Upgrading webpack past what we currently have causes
    # conflicts between the different versions of webpack.  Disable further
    # updates of webpack until we can migrate off @vue/cli-service (which is
    # unlikely to be fixed as it is in maintenance mode).
    dependency-name: "webpack"

# Maintain dependencies for Golang
- package-ecosystem: "gomod"
  directories:
  - "/src/go/*"
  - "/src/go/**/*"
  - "/scripts"
  schedule:
    interval: "daily"
# cooldown:
#   default-days: 7
  open-pull-requests-limit: 12
  labels: ["component/dependencies"]
  ignore:
  - # Swagger dependencies must match whatever the CLI generate.
    dependency-name: "github.com/go-openapi/swag"
  groups:
    golang-x:
      patterns: ["golang.org/x/*"]
    k8s:
      patterns: ["k8s.io/*"]
