env:
  browser: true
  jest: true
  node: true
extends:
  - "@nuxtjs"
  - "plugin:nuxt/recommended"
  - "plugin:vue/essential"
  - "eslint:recommended"
ignorePatterns:
  - "/app/**"
  - "/dist/**"
parserOptions:
  parser: "@babel/eslint-parser"
root: true
rules:
  arrow-parens: [error, as-needed]
  comma-dangle: [error, always-multiline]
  key-spacing: [error, { align: value }]
  node/no-callback-literal: "off"
  no-console: "off"
  no-throw-literal: "off"
  prefer-promise-reject-errors: "off"
  quotes: [warn, single, { avoidEscape: true, allowTemplateLiterals: true}]
  semi: [error, always]
  space-before-function-paren:
    - error
    - { anonymous: never, named: never, asyncArrow: always }
  vue/no-v-html: "off"
