version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - importShadow # "forwarder", "tracker", etc. -- to be resolved later.
        - octalLiteral
        - unnamedResult
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - ^strings\.SplitN$
        - ^os\.FileMode$
        - ^os\.Mkdir(?:All)?$
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
          - gosec
        path: _test\.go
      - # Exclude bodyclose when it's passed to client.ProcessRequestForAPI
        # or client.ProcessRequestForUtility which internally closes the body.
        linters:
          - bodyclose
        path: src/go/rdctl/
        source: client.ProcessRequestFor(API|Utility)\(rdClient.DoRequest(WithPayload)?\(
      - # Exclude ST1005 when it encounters errors starting with proper noun
        linters:
          - staticcheck
        path: src/go/wsl-helper/cmd/kubeconfig.go
        text: 'ST1005:'
        source: errors.New\("Windows
      - # Exclude ST1005 when it encounters errors starting with proper noun
        linters:
          - staticcheck
        path: src/go/rdctl/pkg/lock/lock.go
        text: 'ST1005:'
        source: fmt.Errorf\("Rancher Desktop
      - # Exclude the FIXME comments from upstream
        linters:
          - gocritic
        path: src/go/wsl-helper/pkg/dockerproxy/platform/vsock_linux\.go
        text: todoCommentWithoutDetail
      - # Ignore errors from syscall
        linters:
          - dogsled
        source: ^\s*_, _, _ = .*\.Call\(
      - # Ignore foreign constants
        linters:
          - staticcheck
        path: src/go/rdctl/pkg/process/process_darwin.go
        text: 'ST1003:'
        source: ^\s*(CTL_KERN|KERN_PROCARGS)\s*=
      - # Ignore foreign constants
        linters:
          - staticcheck
        path: src/go/rdctl/pkg/process/process_windows.go
        text: 'ST1003:'
        source: ^\s*type\s+[A-Z0-9_]+\s+struct
      - # Ignore foreign constants
        linters:
          - staticcheck
        path: src/go/rdctl/pkg/process/process_windows.go
        text: 'ST1003:'
        source: ^\s*[A-Z0-9_]+\s+=
      - # Don't de-duplicate different commands.
        linters:
          - dupl
        path: src/go/rdctl/cmd/extension(Install|Uninstall)\.go$
      - # Don't use %q for registry files to avoid escaping backslashes
        linters:
          - gocritic
        path: src/go/rdctl/pkg/reg/reg.go
        text: 'sprintfQuotedString:'
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
