// Code generated by github.com/rancher-sandbox/rancher-desktop/src/go/nerdctl-stub - DO NOT EDIT.

// package main implements a stub for nerdctl
package main

// commands supported by nerdctl; the key here is a space-separated subcommand
// path to reach the given subcommand (where the root command is empty).
var commands = map[string]commandDefinition{

	"": {
		commandPath: "",
		subcommands: map[string]struct{}{
			"run":        {},
			"exec":       {},
			"ps":         {},
			"logs":       {},
			"port":       {},
			"stop":       {},
			"start":      {},
			"kill":       {},
			"rm":         {},
			"pause":      {},
			"unpause":    {},
			"commit":     {},
			"wait":       {},
			"build":      {},
			"images":     {},
			"pull":       {},
			"push":       {},
			"load":       {},
			"save":       {},
			"tag":        {},
			"rmi":        {},
			"events":     {},
			"info":       {},
			"version":    {},
			"inspect":    {},
			"top":        {},
			"login":      {},
			"logout":     {},
			"compose":    {},
			"completion": {},
			"help":       {},
			"h":          {},
			"container":  {},
			"image":      {},
			"network":    {},
			"volume":     {},
			"system":     {},
			"namespace":  {},
		},
		options: map[string]argHandler{
			"--address":           ignoredArgHandler,
			"--cgroup-manager":    ignoredArgHandler,
			"--cni-netconfpath":   ignoredArgHandler,
			"--cni-path":          ignoredArgHandler,
			"--data-root":         ignoredArgHandler,
			"--debug":             nil,
			"--debug-full":        nil,
			"--help":              nil,
			"--host":              ignoredArgHandler,
			"--insecure-registry": nil,
			"--namespace":         ignoredArgHandler,
			"--snapshotter":       ignoredArgHandler,
			"--storage-driver":    ignoredArgHandler,
			"--version":           nil,
			"-H":                  ignoredArgHandler,
			"-a":                  ignoredArgHandler,
			"-h":                  nil,
			"-n":                  ignoredArgHandler,
			"-v":                  nil,
		},
	},

	"run": {
		commandPath: "run",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--cap-add":      ignoredArgHandler,
			"--cap-drop":     ignoredArgHandler,
			"--cgroupns":     ignoredArgHandler,
			"--cidfile":      ignoredArgHandler,
			"--cpu-shares":   ignoredArgHandler,
			"--cpus":         ignoredArgHandler,
			"--cpuset-cpus":  ignoredArgHandler,
			"--detach":       nil,
			"--device":       ignoredArgHandler,
			"--dns":          ignoredArgHandler,
			"--entrypoint":   ignoredArgHandler,
			"--env":          ignoredArgHandler,
			"--env-file":     ignoredArgHandler,
			"--gpus":         ignoredArgHandler,
			"--help":         nil,
			"--hostname":     ignoredArgHandler,
			"--interactive":  nil,
			"--label":        ignoredArgHandler,
			"--label-file":   ignoredArgHandler,
			"--memory":       ignoredArgHandler,
			"--name":         ignoredArgHandler,
			"--net":          ignoredArgHandler,
			"--network":      ignoredArgHandler,
			"--pid":          ignoredArgHandler,
			"--pidfile":      ignoredArgHandler,
			"--pids-limit":   ignoredArgHandler,
			"--privileged":   nil,
			"--publish":      ignoredArgHandler,
			"--pull":         ignoredArgHandler,
			"--read-only":    nil,
			"--restart":      ignoredArgHandler,
			"--rm":           nil,
			"--rootfs":       nil,
			"--runtime":      ignoredArgHandler,
			"--security-opt": ignoredArgHandler,
			"--shm-size":     ignoredArgHandler,
			"--sysctl":       ignoredArgHandler,
			"--tty":          nil,
			"--user":         ignoredArgHandler,
			"--volume":       ignoredArgHandler,
			"--workdir":      ignoredArgHandler,
			"-d":             nil,
			"-e":             ignoredArgHandler,
			"-h":             ignoredArgHandler,
			"-i":             nil,
			"-l":             ignoredArgHandler,
			"-m":             ignoredArgHandler,
			"-p":             ignoredArgHandler,
			"-t":             nil,
			"-u":             ignoredArgHandler,
			"-v":             ignoredArgHandler,
			"-w":             ignoredArgHandler,
		},
	},

	"exec": {
		commandPath: "exec",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--detach":      nil,
			"--env":         ignoredArgHandler,
			"--help":        nil,
			"--interactive": nil,
			"--privileged":  nil,
			"--tty":         nil,
			"--workdir":     ignoredArgHandler,
			"-d":            nil,
			"-e":            ignoredArgHandler,
			"-h":            nil,
			"-i":            nil,
			"-t":            nil,
			"-w":            ignoredArgHandler,
		},
	},

	"ps": {
		commandPath: "ps",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--all":      nil,
			"--format":   ignoredArgHandler,
			"--help":     nil,
			"--no-trunc": nil,
			"--quiet":    nil,
			"-a":         nil,
			"-h":         nil,
			"-q":         nil,
		},
	},

	"logs": {
		commandPath: "logs",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--follow":     nil,
			"--help":       nil,
			"--since":      ignoredArgHandler,
			"--tail":       ignoredArgHandler,
			"--timestamps": nil,
			"--until":      ignoredArgHandler,
			"-f":           nil,
			"-h":           nil,
			"-n":           ignoredArgHandler,
			"-t":           nil,
		},
	},

	"port": {
		commandPath: "port",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"stop": {
		commandPath: "stop",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"--time": ignoredArgHandler,
			"-h":     nil,
			"-t":     ignoredArgHandler,
		},
	},

	"start": {
		commandPath: "start",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"kill": {
		commandPath: "kill",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":   nil,
			"--signal": ignoredArgHandler,
			"-h":       nil,
			"-s":       ignoredArgHandler,
		},
	},

	"rm": {
		commandPath: "rm",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--force":   nil,
			"--help":    nil,
			"--volumes": nil,
			"-f":        nil,
			"-h":        nil,
			"-v":        nil,
		},
	},

	"pause": {
		commandPath: "pause",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"unpause": {
		commandPath: "unpause",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"commit": {
		commandPath: "commit",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--author":  ignoredArgHandler,
			"--help":    nil,
			"--message": ignoredArgHandler,
			"-a":        ignoredArgHandler,
			"-h":        nil,
			"-m":        ignoredArgHandler,
		},
	},

	"wait": {
		commandPath: "wait",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"build": {
		commandPath: "build",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--build-arg":     ignoredArgHandler,
			"--buildkit-host": ignoredArgHandler,
			"--file":          ignoredArgHandler,
			"--help":          nil,
			"--no-cache":      nil,
			"--progress":      ignoredArgHandler,
			"--secret":        ignoredArgHandler,
			"--ssh":           ignoredArgHandler,
			"--tag":           ignoredArgHandler,
			"--target":        ignoredArgHandler,
			"-f":              ignoredArgHandler,
			"-h":              nil,
			"-t":              ignoredArgHandler,
		},
	},

	"images": {
		commandPath: "images",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format":   ignoredArgHandler,
			"--help":     nil,
			"--no-trunc": nil,
			"--quiet":    nil,
			"-h":         nil,
			"-q":         nil,
		},
	},

	"pull": {
		commandPath: "pull",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"push": {
		commandPath: "push",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"load": {
		commandPath: "load",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--all-platforms": nil,
			"--help":          nil,
			"--input":         ignoredArgHandler,
			"-h":              nil,
			"-i":              ignoredArgHandler,
		},
	},

	"save": {
		commandPath: "save",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":   nil,
			"--output": ignoredArgHandler,
			"-h":       nil,
			"-o":       ignoredArgHandler,
		},
	},

	"tag": {
		commandPath: "tag",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"rmi": {
		commandPath: "rmi",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"events": {
		commandPath: "events",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"info": {
		commandPath: "info",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"-f":       ignoredArgHandler,
			"-h":       nil,
		},
	},

	"version": {
		commandPath: "version",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"-f":       ignoredArgHandler,
			"-h":       nil,
		},
	},

	"inspect": {
		commandPath: "inspect",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"--mode": ignoredArgHandler,
			"-h":     nil,
		},
	},

	"top": {
		commandPath: "top",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"login": {
		commandPath: "login",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":           nil,
			"--password":       ignoredArgHandler,
			"--password-stdin": nil,
			"--username":       ignoredArgHandler,
			"-h":               nil,
			"-p":               ignoredArgHandler,
			"-u":               ignoredArgHandler,
		},
	},

	"logout": {
		commandPath: "logout",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"compose": {
		commandPath: "compose",
		subcommands: map[string]struct{}{
			"up":    {},
			"logs":  {},
			"build": {},
			"down":  {},
			"help":  {},
			"h":     {},
		},
		options: map[string]argHandler{
			"--env-file":          ignoredArgHandler,
			"--file":              ignoredArgHandler,
			"--help":              nil,
			"--project-directory": ignoredArgHandler,
			"--project-name":      ignoredArgHandler,
			"-f":                  ignoredArgHandler,
			"-h":                  nil,
			"-p":                  ignoredArgHandler,
		},
	},

	"compose up": {
		commandPath: "compose up",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--build":         nil,
			"--detach":        nil,
			"--help":          nil,
			"--no-color":      nil,
			"--no-log-prefix": nil,
			"-d":              nil,
			"-h":              nil,
		},
	},

	"compose logs": {
		commandPath: "compose logs",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--follow":        nil,
			"--help":          nil,
			"--no-color":      nil,
			"--no-log-prefix": nil,
			"--tail":          ignoredArgHandler,
			"--timestamps":    nil,
			"-f":              nil,
			"-h":              nil,
			"-t":              nil,
		},
	},

	"compose build": {
		commandPath: "compose build",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--build-arg": ignoredArgHandler,
			"--help":      nil,
			"--no-cache":  nil,
			"--progress":  ignoredArgHandler,
			"-h":          nil,
		},
	},

	"compose down": {
		commandPath: "compose down",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":    nil,
			"--volumes": ignoredArgHandler,
			"-h":        nil,
			"-v":        ignoredArgHandler,
		},
	},

	"compose help": {
		commandPath: "compose help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"compose h": {
		commandPath: "compose h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"completion": {
		commandPath: "completion",
		subcommands: map[string]struct{}{
			"bash": {},
			"help": {},
			"h":    {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"completion bash": {
		commandPath: "completion bash",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"completion help": {
		commandPath: "completion help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"completion h": {
		commandPath: "completion h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"help": {
		commandPath: "help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"h": {
		commandPath: "h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container": {
		commandPath: "container",
		subcommands: map[string]struct{}{
			"run":     {},
			"exec":    {},
			"ls":      {},
			"inspect": {},
			"logs":    {},
			"port":    {},
			"rm":      {},
			"stop":    {},
			"start":   {},
			"kill":    {},
			"pause":   {},
			"wait":    {},
			"unpause": {},
			"commit":  {},
			"help":    {},
			"h":       {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container run": {
		commandPath: "container run",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--cap-add":      ignoredArgHandler,
			"--cap-drop":     ignoredArgHandler,
			"--cgroupns":     ignoredArgHandler,
			"--cidfile":      ignoredArgHandler,
			"--cpu-shares":   ignoredArgHandler,
			"--cpus":         ignoredArgHandler,
			"--cpuset-cpus":  ignoredArgHandler,
			"--detach":       nil,
			"--device":       ignoredArgHandler,
			"--dns":          ignoredArgHandler,
			"--entrypoint":   ignoredArgHandler,
			"--env":          ignoredArgHandler,
			"--env-file":     ignoredArgHandler,
			"--gpus":         ignoredArgHandler,
			"--help":         nil,
			"--hostname":     ignoredArgHandler,
			"--interactive":  nil,
			"--label":        ignoredArgHandler,
			"--label-file":   ignoredArgHandler,
			"--memory":       ignoredArgHandler,
			"--name":         ignoredArgHandler,
			"--net":          ignoredArgHandler,
			"--network":      ignoredArgHandler,
			"--pid":          ignoredArgHandler,
			"--pidfile":      ignoredArgHandler,
			"--pids-limit":   ignoredArgHandler,
			"--privileged":   nil,
			"--publish":      ignoredArgHandler,
			"--pull":         ignoredArgHandler,
			"--read-only":    nil,
			"--restart":      ignoredArgHandler,
			"--rm":           nil,
			"--rootfs":       nil,
			"--runtime":      ignoredArgHandler,
			"--security-opt": ignoredArgHandler,
			"--shm-size":     ignoredArgHandler,
			"--sysctl":       ignoredArgHandler,
			"--tty":          nil,
			"--user":         ignoredArgHandler,
			"--volume":       ignoredArgHandler,
			"--workdir":      ignoredArgHandler,
			"-d":             nil,
			"-e":             ignoredArgHandler,
			"-h":             ignoredArgHandler,
			"-i":             nil,
			"-l":             ignoredArgHandler,
			"-m":             ignoredArgHandler,
			"-p":             ignoredArgHandler,
			"-t":             nil,
			"-u":             ignoredArgHandler,
			"-v":             ignoredArgHandler,
			"-w":             ignoredArgHandler,
		},
	},

	"container exec": {
		commandPath: "container exec",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--detach":      nil,
			"--env":         ignoredArgHandler,
			"--help":        nil,
			"--interactive": nil,
			"--privileged":  nil,
			"--tty":         nil,
			"--workdir":     ignoredArgHandler,
			"-d":            nil,
			"-e":            ignoredArgHandler,
			"-h":            nil,
			"-i":            nil,
			"-t":            nil,
			"-w":            ignoredArgHandler,
		},
	},

	"container ls": {
		commandPath: "container ls",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--all":      nil,
			"--format":   ignoredArgHandler,
			"--help":     nil,
			"--no-trunc": nil,
			"--quiet":    nil,
			"-a":         nil,
			"-h":         nil,
			"-q":         nil,
		},
	},

	"container inspect": {
		commandPath: "container inspect",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"--mode": ignoredArgHandler,
			"-h":     nil,
		},
	},

	"container logs": {
		commandPath: "container logs",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--follow":     nil,
			"--help":       nil,
			"--since":      ignoredArgHandler,
			"--tail":       ignoredArgHandler,
			"--timestamps": nil,
			"--until":      ignoredArgHandler,
			"-f":           nil,
			"-h":           nil,
			"-n":           ignoredArgHandler,
			"-t":           nil,
		},
	},

	"container port": {
		commandPath: "container port",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container rm": {
		commandPath: "container rm",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--force":   nil,
			"--help":    nil,
			"--volumes": nil,
			"-f":        nil,
			"-h":        nil,
			"-v":        nil,
		},
	},

	"container stop": {
		commandPath: "container stop",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"--time": ignoredArgHandler,
			"-h":     nil,
			"-t":     ignoredArgHandler,
		},
	},

	"container start": {
		commandPath: "container start",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container kill": {
		commandPath: "container kill",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":   nil,
			"--signal": ignoredArgHandler,
			"-h":       nil,
			"-s":       ignoredArgHandler,
		},
	},

	"container pause": {
		commandPath: "container pause",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container wait": {
		commandPath: "container wait",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container unpause": {
		commandPath: "container unpause",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container commit": {
		commandPath: "container commit",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--author":  ignoredArgHandler,
			"--help":    nil,
			"--message": ignoredArgHandler,
			"-a":        ignoredArgHandler,
			"-h":        nil,
			"-m":        ignoredArgHandler,
		},
	},

	"container help": {
		commandPath: "container help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"container h": {
		commandPath: "container h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image": {
		commandPath: "image",
		subcommands: map[string]struct{}{
			"build":   {},
			"ls":      {},
			"pull":    {},
			"push":    {},
			"load":    {},
			"save":    {},
			"tag":     {},
			"rm":      {},
			"convert": {},
			"inspect": {},
			"help":    {},
			"h":       {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image build": {
		commandPath: "image build",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--build-arg":     ignoredArgHandler,
			"--buildkit-host": ignoredArgHandler,
			"--file":          ignoredArgHandler,
			"--help":          nil,
			"--no-cache":      nil,
			"--progress":      ignoredArgHandler,
			"--secret":        ignoredArgHandler,
			"--ssh":           ignoredArgHandler,
			"--tag":           ignoredArgHandler,
			"--target":        ignoredArgHandler,
			"-f":              ignoredArgHandler,
			"-h":              nil,
			"-t":              ignoredArgHandler,
		},
	},

	"image ls": {
		commandPath: "image ls",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format":   ignoredArgHandler,
			"--help":     nil,
			"--no-trunc": nil,
			"--quiet":    nil,
			"-h":         nil,
			"-q":         nil,
		},
	},

	"image pull": {
		commandPath: "image pull",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image push": {
		commandPath: "image push",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image load": {
		commandPath: "image load",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--all-platforms": nil,
			"--help":          nil,
			"--input":         ignoredArgHandler,
			"-h":              nil,
			"-i":              ignoredArgHandler,
		},
	},

	"image save": {
		commandPath: "image save",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":   nil,
			"--output": ignoredArgHandler,
			"-h":       nil,
			"-o":       ignoredArgHandler,
		},
	},

	"image tag": {
		commandPath: "image tag",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image rm": {
		commandPath: "image rm",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image convert": {
		commandPath: "image convert",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--all-platforms":             nil,
			"--estargz":                   nil,
			"--estargz-chunk-size":        ignoredArgHandler,
			"--estargz-compression-level": ignoredArgHandler,
			"--estargz-record-in":         ignoredArgHandler,
			"--help":                      nil,
			"--oci":                       nil,
			"--platform":                  ignoredArgHandler,
			"--uncompress":                nil,
			"-h":                          nil,
		},
	},

	"image inspect": {
		commandPath: "image inspect",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"--mode": ignoredArgHandler,
			"-h":     nil,
		},
	},

	"image help": {
		commandPath: "image help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"image h": {
		commandPath: "image h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"network": {
		commandPath: "network",
		subcommands: map[string]struct{}{
			"ls":      {},
			"list":    {},
			"inspect": {},
			"create":  {},
			"rm":      {},
			"remove":  {},
			"help":    {},
			"h":       {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"network ls": {
		commandPath: "network ls",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"--quiet":  nil,
			"-h":       nil,
			"-q":       nil,
		},
	},

	"network list": {
		commandPath: "network list",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"--quiet":  nil,
			"-h":       nil,
			"-q":       nil,
		},
	},

	"network inspect": {
		commandPath: "network inspect",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"--mode": ignoredArgHandler,
			"-h":     nil,
		},
	},

	"network create": {
		commandPath: "network create",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":   nil,
			"--label":  ignoredArgHandler,
			"--subnet": ignoredArgHandler,
			"-h":       nil,
		},
	},

	"network rm": {
		commandPath: "network rm",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"network remove": {
		commandPath: "network remove",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"network help": {
		commandPath: "network help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"network h": {
		commandPath: "network h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"volume": {
		commandPath: "volume",
		subcommands: map[string]struct{}{
			"ls":      {},
			"list":    {},
			"inspect": {},
			"create":  {},
			"rm":      {},
			"remove":  {},
			"help":    {},
			"h":       {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"volume ls": {
		commandPath: "volume ls",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"--quiet":  nil,
			"-h":       nil,
			"-q":       nil,
		},
	},

	"volume list": {
		commandPath: "volume list",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"--quiet":  nil,
			"-h":       nil,
			"-q":       nil,
		},
	},

	"volume inspect": {
		commandPath: "volume inspect",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"volume create": {
		commandPath: "volume create",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":  nil,
			"--label": ignoredArgHandler,
			"-h":      nil,
		},
	},

	"volume rm": {
		commandPath: "volume rm",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--force": nil,
			"--help":  nil,
			"-f":      nil,
			"-h":      nil,
		},
	},

	"volume remove": {
		commandPath: "volume remove",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--force": nil,
			"--help":  nil,
			"-f":      nil,
			"-h":      nil,
		},
	},

	"volume help": {
		commandPath: "volume help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"volume h": {
		commandPath: "volume h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"system": {
		commandPath: "system",
		subcommands: map[string]struct{}{
			"events": {},
			"info":   {},
			"help":   {},
			"h":      {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"system events": {
		commandPath: "system events",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"system info": {
		commandPath: "system info",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--format": ignoredArgHandler,
			"--help":   nil,
			"-f":       ignoredArgHandler,
			"-h":       nil,
		},
	},

	"system help": {
		commandPath: "system help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"system h": {
		commandPath: "system h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"namespace": {
		commandPath: "namespace",
		subcommands: map[string]struct{}{
			"ls":   {},
			"list": {},
			"help": {},
			"h":    {},
		},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"namespace ls": {
		commandPath: "namespace ls",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":  nil,
			"--quiet": nil,
			"-h":      nil,
			"-q":      nil,
		},
	},

	"namespace list": {
		commandPath: "namespace list",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help":  nil,
			"--quiet": nil,
			"-h":      nil,
			"-q":      nil,
		},
	},

	"namespace help": {
		commandPath: "namespace help",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},

	"namespace h": {
		commandPath: "namespace h",
		subcommands: map[string]struct{}{},
		options: map[string]argHandler{
			"--help": nil,
			"-h":     nil,
		},
	},
}
