/**
 * @jest-environment node
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  assetChecksum,
  DependencyManifest,
  DownloadContext,
  parseSha256Checksum,
  readDependencyManifest,
  selectAsset,
  selectAssets,
  writeDependencyManifest,
} from '../dependencies';

const sha = (hex: string) => parseSha256Checksum(`sha256:${ hex.padEnd(64, '0') }`);

const manifest: DependencyManifest = {
  helm: {
    version: '4.2.0',
    assets:  [
      { platform: 'linux', arch: 'amd64', url: 'https://get.helm.sh/helm-linux-amd64.tar.gz', checksum: sha('a1') },
      { platform: 'darwin', arch: 'arm64', url: 'https://get.helm.sh/helm-darwin-arm64.tar.gz', checksum: sha('b2') },
    ],
  },
  dockerProvidedCredentialHelpers: {
    version: '0.9.7',
    assets:  [
      { platform: 'linux', arch: 'amd64', url: 'https://example.test/secretservice-amd64', checksum: sha('c3') },
      { platform: 'linux', arch: 'amd64', url: 'https://example.test/pass-amd64', checksum: sha('d4') },
    ],
  },
  wix: {
    version: '3.14.1',
    assets:  [
      { platform: 'windows', url: 'https://example.test/wix314-binaries.zip', checksum: sha('e5') },
    ],
  },
  distro: {
    version: '0.2.8',
    assets:  [
      {
        platform: 'linux', arch: 'amd64', variant: 'raw', url: 'https://example.test/distro.amd64.raw.xz', checksum: sha('f6'),
      },
      {
        platform: 'linux', arch: 'amd64', variant: 'tar', url: 'https://example.test/distro.amd64.tar.xz', checksum: sha('07'),
      },
    ],
  },
};

/** Builds the minimal context the asset selectors read. */
const contextFor = (m: DependencyManifest) => ({ dependencies: m } as DownloadContext);

describe('dependency manifest', () => {
  let tmpDir: string;

  beforeEach(async() => {
    tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'rddepman-test-'));
  });

  afterEach(async() => {
    await fs.promises.rm(tmpDir, { recursive: true, force: true });
  });

  it('round-trips through write and read', async() => {
    const file = path.join(tmpDir, 'dependencies.yaml');

    await writeDependencyManifest(file, manifest);
    const roundTripped = await readDependencyManifest(file);

    expect(roundTripped).toEqual(manifest);
  });

  it('round-trips structured versions (alpineLimaISO, mobyOpenAPISpec)', async() => {
    const file = path.join(tmpDir, 'structured.yaml');
    const structured: DependencyManifest = {
      alpineLimaISO: {
        version: { isoVersion: '0.2.47.rd9', alpineVersion: '3.24.1' },
        assets:  [{ platform: 'linux', arch: 'amd64', url: 'https://example.test/alpine.iso', checksum: sha('11') }],
      },
      mobyOpenAPISpec: {
        version: { apiVersion: '1.55', commit: 'a'.repeat(40) },
        assets:  [{ platform: 'linux', url: 'https://example.test/v1.55.yaml', checksum: sha('22') }],
      },
    };

    await writeDependencyManifest(file, structured);

    expect(await readDependencyManifest(file)).toEqual(structured);
  });

  it('writes the DO NOT EDIT header', async() => {
    const file = path.join(tmpDir, 'dependencies.yaml');

    await writeDependencyManifest(file, manifest);
    const contents = await fs.promises.readFile(file, 'utf-8');

    expect(contents.startsWith('# Regenerated by `yarn rddepman`')).toBe(true);
  });

  it('loads a legacy checksums-schema entry with no assets', async() => {
    const file = path.join(tmpDir, 'legacy.yaml');

    await fs.promises.writeFile(file, 'helm:\n  version: 4.2.0\n  checksums:\n    helm-linux-amd64.tar.gz: sha256:abc\n', 'utf-8');
    const loaded = await readDependencyManifest(file);

    expect(loaded.helm).toEqual({ version: '4.2.0', assets: [] });
  });

  // Versions are quoted because YAML parses a bare `1.0` as a number, which the
  // version check rejects before any asset is parsed.
  it.each([
    ['platform', 'helm:\n  version: "1.0"\n  assets:\n    - { platform: solaris, arch: amd64, url: u, checksum: sha256:abc }\n', /invalid platform "solaris"/],
    ['arch', 'helm:\n  version: "1.0"\n  assets:\n    - { platform: linux, arch: ppc64, url: u, checksum: sha256:abc }\n', /invalid arch "ppc64"/],
    ['url', 'helm:\n  version: "1.0"\n  assets:\n    - { platform: linux, arch: amd64, url: "not a url", checksum: sha256:abc }\n', /invalid url "not a url"/],
    ['checksum', 'helm:\n  version: "1.0"\n  assets:\n    - { platform: linux, arch: amd64, url: "https://example.test/x", checksum: not-a-sha }\n', /Invalid sha256 checksum "not-a-sha"/],
  ])('rejects an asset with an invalid %s', async(_field, yaml, expected) => {
    const file = path.join(tmpDir, 'invalid.yaml');

    await fs.promises.writeFile(file, yaml, 'utf-8');
    await expect(readDependencyManifest(file)).rejects.toThrow(expected);
  });

  it('rejects a version that is not a string', async() => {
    const file = path.join(tmpDir, 'numeric.yaml');

    await fs.promises.writeFile(file, 'helm:\n  version: 1.0\n  assets: []\n', 'utf-8');
    await expect(readDependencyManifest(file)).rejects.toThrow(/invalid version 1; expected a string/);
  });

  it('rejects a mobyOpenAPISpec commit that is not a 40-char SHA', async() => {
    const file = path.join(tmpDir, 'bad-commit.yaml');

    await fs.promises.writeFile(file, 'mobyOpenAPISpec:\n  version:\n    apiVersion: "1.55"\n    commit: main\n  assets: []\n', 'utf-8');
    await expect(readDependencyManifest(file)).rejects.toThrow(/invalid mobyOpenAPISpec commit "main"; expected a 40-char SHA/);
  });
});

describe('selectAsset / selectAssets', () => {
  const context = contextFor(manifest);

  it('selects a single asset by platform and arch', () => {
    const asset = selectAsset(context, 'helm', { platform: 'linux', arch: 'amd64' });

    expect(asset.url).toBe('https://get.helm.sh/helm-linux-amd64.tar.gz');
  });

  it('matches an arch-independent asset against any arch', () => {
    expect(selectAsset(context, 'wix', { platform: 'windows', arch: 'amd64' }).url)
      .toBe('https://example.test/wix314-binaries.zip');
    expect(selectAsset(context, 'wix', { platform: 'windows', arch: 'arm64' }).url)
      .toBe('https://example.test/wix314-binaries.zip');
  });

  it('selects by variant when several share a platform and arch', () => {
    expect(selectAsset(context, 'distro', { platform: 'linux', arch: 'amd64', variant: 'raw' }).url)
      .toBe('https://example.test/distro.amd64.raw.xz');
    expect(selectAsset(context, 'distro', { platform: 'linux', arch: 'amd64', variant: 'tar' }).url)
      .toBe('https://example.test/distro.amd64.tar.xz');
  });

  it('returns every matching asset from selectAssets', () => {
    const assets = selectAssets(context, 'dockerProvidedCredentialHelpers', { platform: 'linux', arch: 'amd64' });

    expect(assets.map(a => a.url)).toEqual([
      'https://example.test/secretservice-amd64',
      'https://example.test/pass-amd64',
    ]);
  });

  it('throws from selectAsset when the match is ambiguous', () => {
    expect(() => selectAsset(context, 'dockerProvidedCredentialHelpers', { platform: 'linux', arch: 'amd64' }))
      .toThrow(/found 2/);
  });

  it('throws when the dependency is absent', () => {
    expect(() => selectAsset(context, 'nonexistent', { platform: 'linux', arch: 'amd64' }))
      .toThrow(/not present/);
  });
});

describe('assetChecksum', () => {
  it('strips the sha256 prefix', () => {
    expect(assetChecksum({ platform: 'linux', url: 'u', checksum: sha('ab') }))
      .toBe('ab'.padEnd(64, '0'));
  });
});
