#!/bin/sh

set -eu

source /etc/rancher/desktop/credfwd

DATA="@-"
# The "list" command doesn't have a payload on STDIN
[ "$1" = "list" ] && DATA=""

exec curl --silent --show-error --user "$CREDFWD_AUTH" --data "$DATA" --noproxy '*' --fail-with-body "$CREDFWD_URL/$1"
