#!/bin/sh

set -eu

command=
validCommands="list | get URL | store '{ ServerURL: URL, user: USER, secret: SECRET }' | erase URL "

usage() {
  echo "Usage: $0 $validCommands"
  exit 1
}

case $# in
  0) usage ;;
  *) command=$1 ; shift ;;
esac

source /etc/rancher/desktop/credfwd
case $command in
  list) arg=""
    ;;
  get|store|erase) case $# in
    0) arg=$(cat) ;;
    1) arg=$1 ;;
    *) echo "Usage: $0 get URL - too many arguments specified ($*)" ; exit 1 ;;
    esac
    ;;
  *) echo "Unrecognized command '$command'." ; usage
    ;;
esac

curl --user "$CREDFWD_AUTH"  --data "${arg}" --noproxy '*' --fail-with-body "$CREDFWD_URL/$command" 2>/dev/null

