#!/bin/sh

# This script is used to launch K3s on WSL2; this is necessary as we need to do
# some mount namespace shenanigans, since we store the data on the WSL shared
# mount (/mnt/wsl/rancher/desktop/) and that can have issues with lingering
# tmpfs mounts after we exit.  This means we need to run this script under
# unshare (to get a private mount namespace), and then we can mark various
# mount points as shared (for kim / buildkit).  Kubelet will internally do some
# tmpfs mounts for volumes (secrets, etc.), which will stay private and go away
# once k3s exits, so that we can delete the data as necessary.

set -o errexit -o nounset -o xtrace

(
    IFS=:
    for dir in / ${DISTRO_DATA_DIRS}; do
        mount --make-shared "${dir}"
    done
)
exec /usr/local/bin/k3s server "$@"
