export const demoMarketplace = {
  summaries: [
    {
      id:                    '',
      name:                  'Epinio',
      containerd_compatible: true,
      slug:                  'ghcr.io/rancher-sandbox/epinio-desktop-extension',
      type:                  'extension',
      publisher:             { name: 'Rancher by SUSE' },
      created_at:            '2022-05-06T00:44:00Z',
      updated_at:            '2023-02-24T10:40:43.666252815Z',
      short_description:     'Push from source to Kubernetes in one step',
      source:                'community',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large:
          'https://desktop.docker.com/extensions/splatform_epinio-docker-desktop/epinio_io/images/icon-epinio.svg',
        small:
          'https://desktop.docker.com/extensions/splatform_epinio-docker-desktop/epinio_io/images/icon-epinio.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                    '',
      name:                  'Logs Explorer',
      containerd_compatible: true,
      slug:                  'docker/logs-explorer-extension',
      type:                  'extension',
      publisher:             { name: 'Docker Inc.' },
      created_at:            '2022-05-06T00:54:00Z',
      updated_at:            '2023-01-06T10:13:10.265019333Z',
      short_description:     'View all your container logs in one place so you can debug and troubleshoot faster.',
      source:                'verified_publisher',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/docker_logs-explorer-extension/docker-extension-screenshots_s3_amazonaws_com/logs-explorer-extension/icon.svg',
        small: 'https://desktop.docker.com/extensions/docker_logs-explorer-extension/docker-extension-screenshots_s3_amazonaws_com/logs-explorer-extension/icon.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'verified_publisher',
    },
    {
      id:                    '',
      name:                  'Tachometer',
      containerd_compatible: true,
      slug:                  'julianb90/tachometer',
      type:                  'extension',
      publisher:             { name: 'julian-b90' },
      created_at:            '2023-04-05T09:04:15.216413557Z',
      updated_at:            '2023-04-06T04:56:11.099459552Z',
      short_description:     'Extension shows real-time cpu and memory usage of containers',
      source:                'community',
      extension_reviewed:    false,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/julianb90_tachometer/raw_githubusercontent_com/julian-b90/tachometer/main/speedometer.png',
        small: 'https://desktop.docker.com/extensions/julianb90_tachometer/raw_githubusercontent_com/julian-b90/tachometer/main/speedometer.png',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                    '',
      name:                  'Dive In',
      containerd_compatible: true,
      slug:                  'prakhar1989/dive-in',
      type:                  'extension',
      publisher:             { name: 'Prakhar Srivastav' },
      created_at:            '2022-12-08T10:21:03.197405487Z',
      updated_at:            '2023-03-18T19:46:15.051297764Z',
      short_description:     'Explore docker images, layer contents, and discover ways to shrink the size of your Docker/OCI image.',
      source:                'community',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/prakhar1989_dive-in/raw_githubusercontent_com/prakhar1989/dive-in/main/scuba.svg',
        small: 'https://desktop.docker.com/extensions/prakhar1989_dive-in/raw_githubusercontent_com/prakhar1989/dive-in/main/scuba.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                    '',
      name:                  'Newman',
      containerd_compatible: true,
      slug:                  'joycelin79/newman-extension',
      type:                  'extension',
      publisher:             { name: 'Postman' },
      created_at:            '2022-11-07T14:05:39.513909337Z',
      updated_at:            '2022-11-10T20:41:11.989880659Z',
      short_description:     'Run your Postman collections from Docker Desktop.',
      source:                'community',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/joycelin79_newman-extension/voyager_postman_com/icon/icon-newman-docker-orange-postman.svg',
        small: 'https://desktop.docker.com/extensions/joycelin79_newman-extension/voyager_postman_com/icon/icon-newman-docker-orange-postman.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                    '',
      name:                  'Resource usage',
      containerd_compatible: true,
      slug:                  'docker/resource-usage-extension',
      type:                  'extension',
      publisher:             { name: 'Docker Inc.' },
      created_at:            '2022-11-03T10:03:31.74779Z',
      updated_at:            '2023-05-25T10:42:09.6547592Z',
      short_description:     'Monitor and manage live data stream for running containers.',
      source:                'verified_publisher',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/docker_resource-usage-extension/docker-extension-screenshots_s3_amazonaws_com/resource-usage-extension/icon.svg',
        small: 'https://desktop.docker.com/extensions/docker_resource-usage-extension/docker-extension-screenshots_s3_amazonaws_com/resource-usage-extension/icon.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'verified_publisher',
    },
    {
      id:                    '',
      name:                  'anchore',
      containerd_compatible: true,
      slug:                  'anchore/docker-desktop-extension',
      type:                  'extension',
      publisher:             { name: 'Anchore Inc.' },
      created_at:            '2022-05-06T00:58:00Z',
      updated_at:            '2022-10-19T17:40:19.947055488Z',
      short_description:     'Content and security analysis for container images',
      source:                'community',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/anchore_docker-desktop-extension/user-images_githubusercontent_com/590471/164125752-b83d973c-f161-4d54-889f-352dee0ec795.svg',
        small: 'https://desktop.docker.com/extensions/anchore_docker-desktop-extension/user-images_githubusercontent_com/590471/164125752-b83d973c-f161-4d54-889f-352dee0ec795.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                    '',
      name:                  'Blockly Automation',
      containerd_compatible: true,
      slug:                  'ignatandrei/blockly-automation',
      type:                  'extension',
      publisher:             { name: 'Andrei Ignat' },
      created_at:            '2023-03-20T10:04:32.721062423Z',
      updated_at:            '2022-06-06T04:25:38.6530251Z',
      short_description:     'A extension that displays lowCode with Blockly for any Docker command',
      source:                'community',
      extension_reviewed:    false,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/ignatandrei_blockly-automation/github_com/ignatandrei/BlocklyAutomation/wiki/imgs/logoBADocker.png',
        small: 'https://desktop.docker.com/extensions/ignatandrei_blockly-automation/github_com/ignatandrei/BlocklyAutomation/wiki/imgs/logoBADocker.png',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                    '',
      name:                  'Disk Usage',
      containerd_compatible: true,
      slug:                  'docker/disk-usage-extension',
      type:                  'extension',
      publisher:             { name: 'Docker Inc.' },
      created_at:            '2022-05-06T00:56:00Z',
      updated_at:            '2023-04-20T08:53:34.112690303Z',
      short_description:     'Optimize your disk space by removing unused objects from Docker Desktop.',
      source:                'verified_publisher',
      extension_reviewed:    true,
      popularity:            0,
      categories:            null,
      operating_systems:     [],
      architectures:         [],
      logo_url:              {
        large: 'https://desktop.docker.com/extensions/docker_disk-usage-extension/docker-extension-screenshots_s3_us-east-1_amazonaws_com/disk-usage-extension/hard-drive.svg',
        small: 'https://desktop.docker.com/extensions/docker_disk-usage-extension/docker-extension-screenshots_s3_us-east-1_amazonaws_com/disk-usage-extension/hard-drive.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'verified_publisher',
    },
  ],
};
