export const demoMarketplace = {
  summaries: [
    {
      id:                 '',
      name:               'Epinio',
      slug:               'ghcr.io/rancher-sandbox/epinio-desktop-extension',
      type:               'extension',
      publisher:          { name: 'Rancher by SUSE' },
      created_at:         '2022-05-06T00:44:00Z',
      updated_at:         '2023-02-24T10:40:43.666252815Z',
      short_description:  'Push from source to Kubernetes in one step',
      source:             'community',
      extension_reviewed: true,
      popularity:         0,
      categories:         null,
      operating_systems:  [],
      architectures:      [],
      logo_url:           {
        large:
          'https://desktop.docker.com/extensions/splatform_epinio-docker-desktop/epinio_io/images/icon-epinio.svg',
        small:
          'https://desktop.docker.com/extensions/splatform_epinio-docker-desktop/epinio_io/images/icon-epinio.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
    {
      id:                 '',
      name:               'Logs Explorer',
      slug:               'docker/logs-explorer-extension',
      type:               'extension',
      publisher:          { name: 'Docker Inc.' },
      created_at:         '2022-05-06T00:54:00Z',
      updated_at:         '2023-01-06T10:13:10.265019333Z',
      short_description:  'View all your container logs in one place so you can debug and troubleshoot faster.',
      source:             'verified_publisher',
      extension_reviewed: true,
      popularity:         0,
      categories:         null,
      operating_systems:  [],
      architectures:      [],
      logo_url:           {
        large: 'https://desktop.docker.com/extensions/docker_logs-explorer-extension/docker-extension-screenshots_s3_amazonaws_com/logs-explorer-extension/icon.svg',
        small: 'https://desktop.docker.com/extensions/docker_logs-explorer-extension/docker-extension-screenshots_s3_amazonaws_com/logs-explorer-extension/icon.svg',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'verified_publisher',
    },
    {
      id:                 '',
      name:               'Tachometer',
      slug:               'julianb90/tachometer',
      type:               'extension',
      publisher:          { name: 'julian-b90' },
      created_at:         '2023-04-05T09:04:15.216413557Z',
      updated_at:         '2023-04-06T04:56:11.099459552Z',
      short_description:  'Extension shows real-time cpu and memory usage of containers',
      source:             'community',
      extension_reviewed: false,
      popularity:         0,
      categories:         null,
      operating_systems:  [],
      architectures:      [],
      logo_url:           {
        large: 'https://desktop.docker.com/extensions/julianb90_tachometer/raw_githubusercontent_com/julian-b90/tachometer/main/speedometer.png',
        small: 'https://desktop.docker.com/extensions/julianb90_tachometer/raw_githubusercontent_com/julian-b90/tachometer/main/speedometer.png',
      },
      certification_status: '',
      star_count:           0,
      filter_type:          'community',
    },
  ],
};
