#!/bin/sh

set -o errexit -o nounset -o pipefail

if [ -n "${XTRACE:-}" ]; then
    set -o xtrace
fi

VERSION="${1}"
CACHE_DIR="${CACHE_DIR:-${2}}"

# Update symlinks for k3s and images to new version
K3S_DIR="${CACHE_DIR}/${VERSION}"
if [ ! -d "${K3S_DIR}" ]; then
    echo "Directory ${K3S_DIR} does not exist"
    exit 1
fi

# Make sure any outdated kubeconfig file is gone
mkdir -p /etc/rancher/k3s
rm -f /etc/rancher/k3s/k3s.yaml

# Add images
IMAGES="/var/lib/rancher/k3s/agent/images"
mkdir -p "${IMAGES}"
ln -s -f "${K3S_DIR}/k3s-airgap-images-amd64.tar" "${IMAGES}"

# Add k3s binary
ln -s -f "${K3S_DIR}/k3s" /usr/local/bin
# The file system may be readonly (on macOS)
chmod a+x "${K3S_DIR}/k3s" || true
