#!/bin/sh

set -o errexit -o nounset -o pipefail

K3S_YAML=/etc/rancher/k3s/k3s.yaml

COUNT=0
MAX=10
while [ ${COUNT} -lt ${MAX} -a ! -f "${K3S_YAML}" ]; do
    sleep 1
    COUNT=$((COUNT+1))
done

if [ -f "${K3S_YAML}" ]; then
    IP=$(ifconfig eth0 | awk '/inet addr/{print substr($2,6)}')
    sed "s/127\.0\.0\.1/${IP}/" "${K3S_YAML}"
else
    >&2 echo "${K3S_YAML} does not exist after waiting ${MAX} seconds"
    exit 1
fi
