name: Get Token
description: >-
  This action attempts to get a token with the requested permissions; if this is
  not running from the upstream repository, it attempts to get the token from a
  secret.  Otherwise, it uses the vault actions.
  This requires permissions set described in
  https://github.com/rancher-eio/read-vault-secrets
inputs:
  token-secret:
    description: Secret to fall back to
    required: true
outputs:
  token:
    description: The GitHub token retrieved
    value: ${{ steps.gen-token.outcome == 'success' && steps.gen-token.outputs.token || steps.get-secret.outputs.token }}
runs:
  using: composite
  steps:
  - id: vault
    name: Read vault secrets
    if: github.repository_owner == 'rancher-sandbox'
    uses: rancher-eio/read-vault-secrets@dfae8acd43a9e170fca5f90168da22f814fe4e9a # main
    with:
      secrets: |
        secret/data/github/repo/${{ github.repository }}/github/app-credentials clientId | CLIENT_ID ;
        secret/data/github/repo/${{ github.repository }}/github/app-credentials privateKey | PRIVATE_KEY
  - id: gen-token
    name: Generate token
    if: steps.vault.outcome == 'success'
    uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
    with:
      client-id: ${{ env.CLIENT_ID }}
      private-key: ${{ env.PRIVATE_KEY }}
  - id: get-secret
    name: Fall back to GitHub-hosted secrets
    if: steps.vault.outcome == 'skipped'
    run: echo "token=${SECRET:?Secret not found}" >> "$GITHUB_OUTPUT"
    shell: bash
    env:
      SECRET: ${{ inputs.token-secret }}
