package main

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// metadataPath returns the path to a locale's metadata file.
func metadataPath(root, locale string) string {
	return filepath.Join(root, translationsDir, "meta", locale+".yaml")
}

// loadMetadata reads a metadata file into a map of dotted keys to English
// source strings. Returns an empty map if the file does not exist.
func loadMetadata(root, locale string) (map[string]string, error) {
	path := metadataPath(root, locale)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return make(map[string]string), nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading metadata %s: %w", path, err)
	}
	return parseMetadata(string(data))
}

// parseMetadata parses a flat YAML mapping of "dotted.key: value" entries.
// Uses the YAML decoder to correctly handle block scalars and quoted values.
func parseMetadata(content string) (map[string]string, error) {
	result := make(map[string]string)
	if err := yaml.Unmarshal([]byte(content), &result); err != nil {
		return nil, fmt.Errorf("parsing metadata: %w", err)
	}
	return result, nil
}

// serializeMetadata marshals a flat key-value map to YAML with a header comment.
func serializeMetadata(locale string, entries map[string]string) ([]byte, error) {
	data, err := yaml.Marshal(entries)
	if err != nil {
		return nil, fmt.Errorf("marshaling metadata: %w", err)
	}
	header := "# English source strings for " + locale + " translations.\n" +
		"# Auto-generated by i18n-report merge. Do not edit.\n"
	return append([]byte(header), data...), nil
}

// writeMetadata writes metadata for a locale based on its translated keys
// and the current English source values.
func writeMetadata(root, locale string, enKeys map[string]string, localeKeys map[string]string) error {
	path := metadataPath(root, locale)

	// Ensure meta directory exists.
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating meta directory: %w", err)
	}

	// Build entries: only keys that exist in both locale and English.
	entries := make(map[string]string)
	for _, key := range sortedKeys(localeKeys) {
		if enValue, exists := enKeys[key]; exists {
			entries[key] = enValue
		}
	}

	data, err := serializeMetadata(locale, entries)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("writing metadata %s: %w", path, err)
	}
	return nil
}

// removeMetadataKeys removes the given keys from a locale's metadata file.
// If the metadata file does not exist, this is a no-op.
func removeMetadataKeys(root, locale string, keys map[string]bool) error {
	meta, err := loadMetadata(root, locale)
	if err != nil {
		return err
	}
	if len(meta) == 0 {
		return nil
	}

	changed := false
	for k := range keys {
		if _, exists := meta[k]; exists {
			delete(meta, k)
			changed = true
		}
	}
	if !changed {
		return nil
	}

	data, err := serializeMetadata(locale, meta)
	if err != nil {
		return err
	}
	path := metadataPath(root, locale)
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("writing metadata %s: %w", path, err)
	}
	return nil
}

// generateMetadata computes and writes metadata for a locale from its
// current translation file and the English source. Used for bootstrapping
// existing locales that do not yet have metadata files.
func generateMetadata(root, locale string) error {
	enPath := translationsPath(root, "en-us.yaml")
	localePath := translationsPath(root, locale+".yaml")

	enKeys, err := loadYAMLFlat(enPath)
	if err != nil {
		return err
	}
	localeKeys, err := loadYAMLFlat(localePath)
	if err != nil {
		return err
	}

	return writeMetadata(root, locale, enKeys, localeKeys)
}
