linters:
  presets:
    - bugs
    - comment
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    # golangci-lint includes deprecated linters by default in presets.
    - contextcheck
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    # linters that are not useful
    - exhaustruct # Many structs have optional fields
    - musttag
    - nosnakecase # Catches imported constants like SO_LINGER
    - wrapcheck # No need to always wrap errors
    - depguard # Requires configuration and by default only allows stdlib imports
    - dupword # It interferes with duplicate words in comments
    - wsl
linters-settings:
  mnd:
    ignored-functions:
    - "net.IPv4"
  govet:
    disable:
    - lostcancel # Not tracking cancel usage correctly.
