# This workflow builds the Rancher Desktop Extensions Host APIs testing image
# and publishes it.

name: RDX Host APIs Testing image
on:
  push:
    branches: [ main ]
    paths: [ 'bats/tests/extensions/testdata/**' ]
  workflow_dispatch: {}
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
    - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
    - uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}/rdx-host-api-test
        tags: type=raw,value=latest,enable={{ is_default_branch }}
    - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        build-args: variant=host-apis
        context: bats/tests/extensions/testdata
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
